// templates/node-angular/src/app/app.component.ts
import { Component, OnInit } from '@angular/core';

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.css'],
  standalone: true, 
})
export class AppComponent implements OnInit {
  oracleLogo = '/assets/ORCL.svg'
  angularLogo = '/assets/angular.svg'
  title: string = 'node-angular';
  isConnected?: boolean;


  async ngOnInit() {
    try {
      const response = await fetch('http://localhost:3000/api/connection/status');
      const data = await response.json();
      if (data.status === 'ok') {
        this.isConnected = true;
      } else {
        this.isConnected = undefined;
      }
    } catch (error) {
      console.error('Error fetching connection status:', error);
      this.isConnected = undefined;
    }
  }
  
  get checkingConnection() {
    if (this.isConnected === undefined) {
      return 'Checking connection status...';
    } else if (this.isConnected) {
      return 'Database is working!';
    } else {
      return 'Something is wrong with the database!';
    }
  }
}

<div id="root">
  <div>
    <a href="https://www.oracle.com/uk/database/" target="_blank">
      <img src="{{ oracleLogo }}" class="logo" alt="Oracle logo" />
    </a>
    <a href="https://angular.io/" target="_blank">
      <img src="{{ angularLogo }}" class="logo angular" alt="angular logo" />
    </a>
  </div>
  <h1>{{ checkingConnection}}</h1>
  <div class="card">
    <p>
      Edit <code>src/app.component.ts</code> and save to test HMR
    </p>
  </div>
  <p class="read-the-docs">
    Click on the Oracle and React logos to learn more
  </p>
</div>

// templates/node-react/src/App.jsx
/*
**
** Copyright (c) 2024, Oracle and/or its affiliates.
** All rights reserved
** Licensed under the Universal Permissive License v 1.0 as shown at https://oss.oracle.com/licenses/upl/
*/
import { useState, useEffect } from 'react'
import reactLogo from './assets/react.svg'
import OracleLogo from './assets/ORCL.svg'
import './App.css'

function App() {
  const [isConnected, setIsConnected] = useState()
  useEffect(() => {
    const checkConnection = async () => {
      try {
        const response = await fetch('http://localhost:3000/api/connection/status');
        const data = await response.json();

        console.log(data);

        if (data.status === 'ok') {
          setIsConnected(true);
        } else {
          setIsConnected(false);
        }
      } catch (error) {
        console.error('Error fetching connection status:', error);
        setIsConnected(false);
      }
    };

    checkConnection();
  }, []);

  const checkingConnection = (isConnected) => {
    if (isConnected == undefined) {
      return 'Checking connection status...'
    } else if (isConnected) {
      return 'Database is working!'
    } else {
      return 'Something is wrong with the database!'
    }

  }

  return (
    <>
      <div>
        <a href="https://www.oracle.com/uk/database/" target="_blank">
          <img src={OracleLogo} className="logo" alt="Vite logo" />
        </a>
        <a href="https://react.dev" target="_blank">
          <img src={reactLogo} className="logo react" alt="React logo" />
        </a>
      </div>
      <h1>{checkingConnection(isConnected)}</h1>
      <div className="card">
        <p>
          Edit <code>src/App.jsx</code> and save to test HMR
        </p>
      </div>
      <p className="read-the-docs">
        Click on the Oracle and React logos to learn more
      </p>
    </>
  )
}

export default App
